#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "
👎 Bad commit message: '$(head -1 "$1")'

💡 Allowed format is:
type(scope): commit message

Types: build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test
Scope: <package-name> (setting this is optional)

--- Example
feat: implement user management
---

More at https://www.conventionalcommits.org/en/v1.0.0/#summary
     ">&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi
